### ISSUE TITLE
Nullpointer in Protege 5.0.0 Beta 17

### ISSUE THREAD

**Issue by JensLehmann** [SmartDataAnalytics/DL-Learner-Protege-Plugin#1]
File: carcinogenesis.owl
Reasoner: Hermit
Selected Class: Atom
Axiom Type: EquivalentTo

Clicking "suggest equivalent class expressions" returns:

NullPointerException: null
    org.dllearner.reasoning.ClosedWorldReasoner.hasTypeImpl(ClosedWorldReasoner.java:703)
    org.dllearner.core.AbstractReasonerComponent.hasType(AbstractReasonerComponent.java:439)
    org.dllearner.learningproblems.ClassLearningProblem.getAccuracyOrTooWeakExact(ClassLearningProblem.java:593)
    org.dllearner.learningproblems.ClassLearningProblem.getAccuracyOrTooWeak(ClassLearningProblem.java:302)
    org.dllearner.algorithms.celoe.CELOE.addNode(CELOE.java:678)
    org.dllearner.algorithms.celoe.CELOE.start(CELOE.java:556)
    org.dllearner.tools.protege.Manager.startLearning(Manager.java:214)
    org.dllearner.tools.protege.ActionHandler$SuggestionRetriever.doInBackground(ActionHandler.java:214)
    org.dllearner.tools.protege.ActionHandler$SuggestionRetriever.doInBackground(ActionHandler.java:168)
    javax.swing.SwingWorker$1.call(SwingWorker.java:296)
    java.util.concurrent.FutureTask.run(FutureTask.java:262)
    javax.swing.SwingWorker.run(SwingWorker.java:335)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    java.lang.Thread.run(Thread.java:745)

**Comment by LorenzBuehmann** [comment]
Solved by moving to DL-Learner 1.3.0
